import { escapeHtml } from './templates.mjs';

export const galleryImages = [
    { slug: 'team', title: 'The Valtron team', alt: 'Valtron team gathered inside the factory beneath the company banner', width: 704, height: 400 },
    { slug: 'unit-one', title: 'Unit 1', alt: 'Exterior of the Valtron Unit 1 factory with staff at the entrance', width: 579, height: 385 },
    { slug: 'unit-two', title: 'Unit 2', alt: 'A large flanged component being lifted outside the Valtron Unit 2 entrance', width: 577, height: 385 },
    { slug: 'heating', title: 'Heating station', alt: 'Heated metal component positioned in industrial heating equipment', width: 642, height: 347 },
    { slug: 'press', title: 'Press operation', alt: 'Operator working at a large industrial press', width: 521, height: 347 },
    { slug: 'forming', title: 'Component forming', alt: 'Worker handling a circular metal component at a forming machine', width: 386, height: 285 },
    { slug: 'inspection', title: 'Flange preparation', alt: 'Two staff members handling flanges arranged on a wooden crate', width: 381, height: 285 },
    { slug: 'machining', title: 'Machining station', alt: 'Operator at a machining centre beside trays of metal components', width: 385, height: 285 },
    { slug: 'flanges', title: 'Finished flanges', alt: 'Close view of machined flanges with bolt holes and protected bores', width: 172, height: 227 },
    { slug: 'workshop', title: 'Workshop overview', alt: 'Machinery and trays of flanges on the workshop floor', width: 305, height: 227 },
    { slug: 'forging', title: 'Hot-metal working', alt: 'Worker using tools beside a glowing metal component under a press', width: 331, height: 227 },
    { slug: 'shop-floor', title: 'On the shop floor', alt: 'Valtron staff standing between machining stations and packed components', width: 329, height: 227 }
];

const photograph = (image, index) => `<figure class="vf-gallery-photo" style="--photo-width:${image.width}px"><a href="img/gallery/${image.slug}.png" data-gallery-image aria-label="View ${escapeHtml(image.title)}" title="View ${escapeHtml(image.title)}"><img src="img/gallery/${image.slug}.png" width="${image.width}" height="${image.height}" alt="${escapeHtml(image.alt)}" loading="${index === 0 ? 'eager' : 'lazy'}"><span class="vf-gallery-expand" aria-hidden="true"><i class="fas fa-search-plus"></i></span></a><figcaption><span>${String(index + 1).padStart(2, '0')}</span><h3>${escapeHtml(image.title)}</h3></figcaption></figure>`;

export function galleryPage() {
    const section = (id, title, start, end, columns) => `<section class="vf-gallery-section" aria-labelledby="${id}"><div class="vf-gallery-section-heading"><h2 id="${id}">${title}</h2><span>${String(start + 1).padStart(2, '0')} &ndash; ${String(end).padStart(2, '0')}</span></div><div class="vf-gallery-grid vf-gallery-grid-${columns}">${galleryImages.slice(start, end).map((image, index) => photograph(image, start + index)).join('')}</div></section>`;
    return `<div class="vf-gallery vf-wrap"><header class="vf-gallery-intro"><div><p class="vf-eyebrow">Valtron Forge &amp; Fittings</p><h1>Factory Gallery</h1><p>People, facilities and work on the shop floor.</p></div><a class="vf-text-link" href="Valtron%20Forge_0222.pdf#page=3">View Catalogue <i class="fas fa-arrow-right" aria-hidden="true"></i></a></header><section class="vf-gallery-team" aria-labelledby="gallery-team"><div><p class="vf-eyebrow">Behind the work</p><h2 id="gallery-team">The people.<br> The process.<br> The finished connection.</h2><p>Inside Valtron's facilities, from component forming and machining to flange preparation.</p><p class="vf-gallery-source">From the Valtron company catalogue<br>Factory Images / Page 03</p></div>${photograph(galleryImages[0], 0)}</section>${section('gallery-facilities', 'Our facilities', 1, 3, 2)}${section('gallery-production', 'Production floor', 3, 5, 2)}${section('gallery-components', 'Working the details', 5, 8, 3)}${section('gallery-workshop', 'Around the workshop', 8, 12, 4)}<div class="vf-gallery-enquiry"><div><p class="vf-eyebrow">Your next connection</p><h2>Discuss your flange requirements.</h2></div><a class="vf-button" href="contact.html">Contact Valtron <i class="fas fa-arrow-right" aria-hidden="true"></i></a></div></div><dialog class="vf-gallery-viewer" aria-labelledby="gallery-viewer-title"><div class="vf-gallery-viewer-bar"><h2 id="gallery-viewer-title">The Valtron team</h2><a class="vf-gallery-control" data-gallery-original href="img/gallery/team.png" title="Open original image" aria-label="Open original image"><i class="fas fa-external-link-alt" aria-hidden="true"></i></a><button type="button" class="vf-gallery-control" data-gallery-close title="Close image" aria-label="Close image"><i class="fas fa-times" aria-hidden="true"></i></button></div><div class="vf-gallery-viewer-stage"><img src="img/gallery/team.png" alt="Valtron team gathered inside the factory"></div><div class="vf-gallery-viewer-bottom"><button type="button" class="vf-gallery-control" data-gallery-previous title="Previous image" aria-label="Previous image"><i class="fas fa-arrow-left" aria-hidden="true"></i></button><span data-gallery-position aria-live="polite"></span><button type="button" class="vf-gallery-control" data-gallery-next title="Next image" aria-label="Next image"><i class="fas fa-arrow-right" aria-hidden="true"></i></button></div></dialog>`;
}